//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GiraphParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGiraphParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class GiraphParserBaseListener : IGiraphParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] GiraphParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] GiraphParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] GiraphParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] GiraphParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDcls([NotNull] GiraphParser.DclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDcls([NotNull] GiraphParser.DclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.objectDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectDcl([NotNull] GiraphParser.ObjectDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.objectDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectDcl([NotNull] GiraphParser.ObjectDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variableDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDcl([NotNull] GiraphParser.VariableDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variableDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDcl([NotNull] GiraphParser.VariableDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphInitDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphInitDcl([NotNull] GiraphParser.GraphInitDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphInitDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphInitDcl([NotNull] GiraphParser.GraphInitDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphDclBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphDclBlock([NotNull] GiraphParser.GraphDclBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphDclBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphDclBlock([NotNull] GiraphParser.GraphDclBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.vertexDcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVertexDcls([NotNull] GiraphParser.VertexDclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.vertexDcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVertexDcls([NotNull] GiraphParser.VertexDclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.vertexDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVertexDcl([NotNull] GiraphParser.VertexDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.vertexDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVertexDcl([NotNull] GiraphParser.VertexDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.edgeDcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEdgeDcls([NotNull] GiraphParser.EdgeDclsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.edgeDcls"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEdgeDcls([NotNull] GiraphParser.EdgeDclsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.edgeDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEdgeDcl([NotNull] GiraphParser.EdgeDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.edgeDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEdgeDcl([NotNull] GiraphParser.EdgeDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GiraphParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GiraphParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] GiraphParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] GiraphParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.expressionExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionExtension([NotNull] GiraphParser.ExpressionExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.expressionExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionExtension([NotNull] GiraphParser.ExpressionExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] GiraphParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] GiraphParser.QueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.querySC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuerySC([NotNull] GiraphParser.QuerySCContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.querySC"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuerySC([NotNull] GiraphParser.QuerySCContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.noReturnQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoReturnQuery([NotNull] GiraphParser.NoReturnQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.noReturnQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoReturnQuery([NotNull] GiraphParser.NoReturnQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.returnQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnQuery([NotNull] GiraphParser.ReturnQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.returnQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnQuery([NotNull] GiraphParser.ReturnQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] GiraphParser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] GiraphParser.OperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.simpleOperators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleOperators([NotNull] GiraphParser.SimpleOperatorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.simpleOperators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleOperators([NotNull] GiraphParser.SimpleOperatorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.advancedOperators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdvancedOperators([NotNull] GiraphParser.AdvancedOperatorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.advancedOperators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdvancedOperators([NotNull] GiraphParser.AdvancedOperatorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.formalParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParams([NotNull] GiraphParser.FormalParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.formalParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParams([NotNull] GiraphParser.FormalParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.formalParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParam([NotNull] GiraphParser.FormalParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.formalParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParam([NotNull] GiraphParser.FormalParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.functionDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDcl([NotNull] GiraphParser.FunctionDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.functionDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDcl([NotNull] GiraphParser.FunctionDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlock([NotNull] GiraphParser.CodeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlock([NotNull] GiraphParser.CodeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.returnBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnBlock([NotNull] GiraphParser.ReturnBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.returnBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnBlock([NotNull] GiraphParser.ReturnBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.runFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRunFunction([NotNull] GiraphParser.RunFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.runFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRunFunction([NotNull] GiraphParser.RunFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.codeBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlockContent([NotNull] GiraphParser.CodeBlockContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.codeBlockContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlockContent([NotNull] GiraphParser.CodeBlockContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.varOrConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrConst([NotNull] GiraphParser.VarOrConstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.varOrConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrConst([NotNull] GiraphParser.VarOrConstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.varOrFuncOrConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrFuncOrConst([NotNull] GiraphParser.VarOrFuncOrConstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.varOrFuncOrConst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrFuncOrConst([NotNull] GiraphParser.VarOrFuncOrConstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] GiraphParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] GiraphParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variableFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableFunc([NotNull] GiraphParser.VariableFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variableFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableFunc([NotNull] GiraphParser.VariableFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dotFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotFunction([NotNull] GiraphParser.DotFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dotFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotFunction([NotNull] GiraphParser.DotFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] GiraphParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] GiraphParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] GiraphParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] GiraphParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] GiraphParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] GiraphParser.IntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.floatnum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatnum([NotNull] GiraphParser.FloatnumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.floatnum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatnum([NotNull] GiraphParser.FloatnumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] GiraphParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] GiraphParser.BoolContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.objects"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjects([NotNull] GiraphParser.ObjectsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.objects"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjects([NotNull] GiraphParser.ObjectsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.ifElseIfElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfElseIfElse([NotNull] GiraphParser.IfElseIfElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.ifElseIfElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfElseIfElse([NotNull] GiraphParser.IfElseIfElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.boolComparisons"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolComparisons([NotNull] GiraphParser.BoolComparisonsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.boolComparisons"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolComparisons([NotNull] GiraphParser.BoolComparisonsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] GiraphParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] GiraphParser.PredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.predicateCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateCall([NotNull] GiraphParser.PredicateCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.predicateCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateCall([NotNull] GiraphParser.PredicateCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.where"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere([NotNull] GiraphParser.WhereContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.where"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere([NotNull] GiraphParser.WhereContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.andOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndOr([NotNull] GiraphParser.AndOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.andOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndOr([NotNull] GiraphParser.AndOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtend([NotNull] GiraphParser.ExtendContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extend"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtend([NotNull] GiraphParser.ExtendContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect([NotNull] GiraphParser.SelectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.select"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect([NotNull] GiraphParser.SelectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.selectAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectAll([NotNull] GiraphParser.SelectAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.selectAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectAll([NotNull] GiraphParser.SelectAllContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddQuery([NotNull] GiraphParser.AddQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddQuery([NotNull] GiraphParser.AddQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addToGraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddToGraph([NotNull] GiraphParser.AddToGraphContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addToGraph"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddToGraph([NotNull] GiraphParser.AddToGraphContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addToColl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddToColl([NotNull] GiraphParser.AddToCollContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addToColl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddToColl([NotNull] GiraphParser.AddToCollContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.loopDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopDcl([NotNull] GiraphParser.LoopDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.loopDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopDcl([NotNull] GiraphParser.LoopDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.foreachLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachLoop([NotNull] GiraphParser.ForeachLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.foreachLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachLoop([NotNull] GiraphParser.ForeachLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] GiraphParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] GiraphParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.doWhileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoWhileLoop([NotNull] GiraphParser.DoWhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.doWhileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoWhileLoop([NotNull] GiraphParser.DoWhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoop([NotNull] GiraphParser.ForLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoop([NotNull] GiraphParser.ForLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForCondition([NotNull] GiraphParser.ForConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForCondition([NotNull] GiraphParser.ForConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.assignmentParant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentParant([NotNull] GiraphParser.AssignmentParantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.assignmentParant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentParant([NotNull] GiraphParser.AssignmentParantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forConditionInside"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForConditionInside([NotNull] GiraphParser.ForConditionInsideContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forConditionInside"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForConditionInside([NotNull] GiraphParser.ForConditionInsideContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperation([NotNull] GiraphParser.OperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.operation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperation([NotNull] GiraphParser.OperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.inlineDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineDcl([NotNull] GiraphParser.InlineDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.inlineDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineDcl([NotNull] GiraphParser.InlineDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.foreachCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachCondition([NotNull] GiraphParser.ForeachConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.foreachCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachCondition([NotNull] GiraphParser.ForeachConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.allType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllType([NotNull] GiraphParser.AllTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.allType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllType([NotNull] GiraphParser.AllTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.allTypeWithColl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllTypeWithColl([NotNull] GiraphParser.AllTypeWithCollContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.allTypeWithColl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllTypeWithColl([NotNull] GiraphParser.AllTypeWithCollContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collectionDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollectionDcl([NotNull] GiraphParser.CollectionDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collectionDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollectionDcl([NotNull] GiraphParser.CollectionDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collectionAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollectionAssignment([NotNull] GiraphParser.CollectionAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collectionAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollectionAssignment([NotNull] GiraphParser.CollectionAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetQuery([NotNull] GiraphParser.SetQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetQuery([NotNull] GiraphParser.SetQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphSetQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGraphSetQuery([NotNull] GiraphParser.GraphSetQueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphSetQuery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGraphSetQuery([NotNull] GiraphParser.GraphSetQueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setExpressionAtri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExpressionAtri([NotNull] GiraphParser.SetExpressionAtriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setExpressionAtri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExpressionAtri([NotNull] GiraphParser.SetExpressionAtriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setExpressionVari"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExpressionVari([NotNull] GiraphParser.SetExpressionVariContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setExpressionVari"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExpressionVari([NotNull] GiraphParser.SetExpressionVariContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.compoundAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundAssign([NotNull] GiraphParser.CompoundAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.compoundAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundAssign([NotNull] GiraphParser.CompoundAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] GiraphParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] GiraphParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setOneAttri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetOneAttri([NotNull] GiraphParser.SetOneAttriContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setOneAttri"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetOneAttri([NotNull] GiraphParser.SetOneAttriContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collNoReturnOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollNoReturnOps([NotNull] GiraphParser.CollNoReturnOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collNoReturnOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollNoReturnOps([NotNull] GiraphParser.CollNoReturnOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collReturnOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCollReturnOps([NotNull] GiraphParser.CollReturnOpsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collReturnOps"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCollReturnOps([NotNull] GiraphParser.CollReturnOpsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.enqueueOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnqueueOP([NotNull] GiraphParser.EnqueueOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.enqueueOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnqueueOP([NotNull] GiraphParser.EnqueueOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dequeueOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDequeueOP([NotNull] GiraphParser.DequeueOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dequeueOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDequeueOP([NotNull] GiraphParser.DequeueOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.popOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPopOP([NotNull] GiraphParser.PopOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.popOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPopOP([NotNull] GiraphParser.PopOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.pushOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPushOP([NotNull] GiraphParser.PushOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.pushOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPushOP([NotNull] GiraphParser.PushOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extractMinOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtractMinOP([NotNull] GiraphParser.ExtractMinOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extractMinOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtractMinOP([NotNull] GiraphParser.ExtractMinOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extractMaxOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtractMaxOP([NotNull] GiraphParser.ExtractMaxOPContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extractMaxOP"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtractMaxOP([NotNull] GiraphParser.ExtractMaxOPContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] GiraphParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] GiraphParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.printOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintOptions([NotNull] GiraphParser.PrintOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.printOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintOptions([NotNull] GiraphParser.PrintOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.printOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintOption([NotNull] GiraphParser.PrintOptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.printOption"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintOption([NotNull] GiraphParser.PrintOptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] GiraphParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] GiraphParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dequeueOPOneLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDequeueOPOneLine([NotNull] GiraphParser.DequeueOPOneLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dequeueOPOneLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDequeueOPOneLine([NotNull] GiraphParser.DequeueOPOneLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.commentLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommentLine([NotNull] GiraphParser.CommentLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.commentLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommentLine([NotNull] GiraphParser.CommentLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.comments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComments([NotNull] GiraphParser.CommentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.comments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComments([NotNull] GiraphParser.CommentsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
