//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GiraphParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GiraphParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IGiraphParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] GiraphParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] GiraphParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] GiraphParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] GiraphParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDcls([NotNull] GiraphParser.DclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDcls([NotNull] GiraphParser.DclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.objectDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectDcl([NotNull] GiraphParser.ObjectDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.objectDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectDcl([NotNull] GiraphParser.ObjectDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variableDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDcl([NotNull] GiraphParser.VariableDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variableDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDcl([NotNull] GiraphParser.VariableDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphInitDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphInitDcl([NotNull] GiraphParser.GraphInitDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphInitDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphInitDcl([NotNull] GiraphParser.GraphInitDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphDclBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphDclBlock([NotNull] GiraphParser.GraphDclBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphDclBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphDclBlock([NotNull] GiraphParser.GraphDclBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.vertexDcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVertexDcls([NotNull] GiraphParser.VertexDclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.vertexDcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVertexDcls([NotNull] GiraphParser.VertexDclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.vertexDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVertexDcl([NotNull] GiraphParser.VertexDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.vertexDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVertexDcl([NotNull] GiraphParser.VertexDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.edgeDcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEdgeDcls([NotNull] GiraphParser.EdgeDclsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.edgeDcls"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEdgeDcls([NotNull] GiraphParser.EdgeDclsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.edgeDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEdgeDcl([NotNull] GiraphParser.EdgeDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.edgeDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEdgeDcl([NotNull] GiraphParser.EdgeDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GiraphParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GiraphParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GiraphParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GiraphParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.expressionExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionExtension([NotNull] GiraphParser.ExpressionExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.expressionExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionExtension([NotNull] GiraphParser.ExpressionExtensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] GiraphParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] GiraphParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.querySC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuerySC([NotNull] GiraphParser.QuerySCContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.querySC"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuerySC([NotNull] GiraphParser.QuerySCContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.noReturnQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoReturnQuery([NotNull] GiraphParser.NoReturnQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.noReturnQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoReturnQuery([NotNull] GiraphParser.NoReturnQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.returnQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnQuery([NotNull] GiraphParser.ReturnQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.returnQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnQuery([NotNull] GiraphParser.ReturnQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] GiraphParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] GiraphParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.simpleOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleOperators([NotNull] GiraphParser.SimpleOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.simpleOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleOperators([NotNull] GiraphParser.SimpleOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.advancedOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdvancedOperators([NotNull] GiraphParser.AdvancedOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.advancedOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdvancedOperators([NotNull] GiraphParser.AdvancedOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.formalParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParams([NotNull] GiraphParser.FormalParamsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.formalParams"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParams([NotNull] GiraphParser.FormalParamsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.formalParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParam([NotNull] GiraphParser.FormalParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.formalParam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParam([NotNull] GiraphParser.FormalParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.functionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDcl([NotNull] GiraphParser.FunctionDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.functionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDcl([NotNull] GiraphParser.FunctionDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlock([NotNull] GiraphParser.CodeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlock([NotNull] GiraphParser.CodeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.returnBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnBlock([NotNull] GiraphParser.ReturnBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.returnBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnBlock([NotNull] GiraphParser.ReturnBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.runFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRunFunction([NotNull] GiraphParser.RunFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.runFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRunFunction([NotNull] GiraphParser.RunFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.codeBlockContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlockContent([NotNull] GiraphParser.CodeBlockContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.codeBlockContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlockContent([NotNull] GiraphParser.CodeBlockContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.varOrConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrConst([NotNull] GiraphParser.VarOrConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.varOrConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrConst([NotNull] GiraphParser.VarOrConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.varOrFuncOrConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarOrFuncOrConst([NotNull] GiraphParser.VarOrFuncOrConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.varOrFuncOrConst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarOrFuncOrConst([NotNull] GiraphParser.VarOrFuncOrConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] GiraphParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] GiraphParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.variableFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableFunc([NotNull] GiraphParser.VariableFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.variableFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableFunc([NotNull] GiraphParser.VariableFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dotFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotFunction([NotNull] GiraphParser.DotFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dotFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotFunction([NotNull] GiraphParser.DotFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] GiraphParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] GiraphParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] GiraphParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] GiraphParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] GiraphParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] GiraphParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.floatnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatnum([NotNull] GiraphParser.FloatnumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.floatnum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatnum([NotNull] GiraphParser.FloatnumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool([NotNull] GiraphParser.BoolContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool([NotNull] GiraphParser.BoolContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.objects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjects([NotNull] GiraphParser.ObjectsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.objects"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjects([NotNull] GiraphParser.ObjectsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.ifElseIfElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseIfElse([NotNull] GiraphParser.IfElseIfElseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.ifElseIfElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseIfElse([NotNull] GiraphParser.IfElseIfElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.boolComparisons"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolComparisons([NotNull] GiraphParser.BoolComparisonsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.boolComparisons"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolComparisons([NotNull] GiraphParser.BoolComparisonsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] GiraphParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] GiraphParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.predicateCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateCall([NotNull] GiraphParser.PredicateCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.predicateCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateCall([NotNull] GiraphParser.PredicateCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.where"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere([NotNull] GiraphParser.WhereContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.where"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere([NotNull] GiraphParser.WhereContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.andOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndOr([NotNull] GiraphParser.AndOrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.andOr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndOr([NotNull] GiraphParser.AndOrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extend"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtend([NotNull] GiraphParser.ExtendContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extend"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtend([NotNull] GiraphParser.ExtendContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect([NotNull] GiraphParser.SelectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect([NotNull] GiraphParser.SelectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.selectAll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectAll([NotNull] GiraphParser.SelectAllContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.selectAll"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectAll([NotNull] GiraphParser.SelectAllContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddQuery([NotNull] GiraphParser.AddQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddQuery([NotNull] GiraphParser.AddQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addToGraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddToGraph([NotNull] GiraphParser.AddToGraphContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addToGraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddToGraph([NotNull] GiraphParser.AddToGraphContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.addToColl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddToColl([NotNull] GiraphParser.AddToCollContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.addToColl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddToColl([NotNull] GiraphParser.AddToCollContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.loopDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopDcl([NotNull] GiraphParser.LoopDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.loopDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopDcl([NotNull] GiraphParser.LoopDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.foreachLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachLoop([NotNull] GiraphParser.ForeachLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.foreachLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachLoop([NotNull] GiraphParser.ForeachLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] GiraphParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] GiraphParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.doWhileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileLoop([NotNull] GiraphParser.DoWhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.doWhileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileLoop([NotNull] GiraphParser.DoWhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] GiraphParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] GiraphParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForCondition([NotNull] GiraphParser.ForConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForCondition([NotNull] GiraphParser.ForConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.assignmentParant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentParant([NotNull] GiraphParser.AssignmentParantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.assignmentParant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentParant([NotNull] GiraphParser.AssignmentParantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.forConditionInside"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForConditionInside([NotNull] GiraphParser.ForConditionInsideContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.forConditionInside"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForConditionInside([NotNull] GiraphParser.ForConditionInsideContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] GiraphParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] GiraphParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.inlineDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineDcl([NotNull] GiraphParser.InlineDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.inlineDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineDcl([NotNull] GiraphParser.InlineDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.foreachCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachCondition([NotNull] GiraphParser.ForeachConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.foreachCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachCondition([NotNull] GiraphParser.ForeachConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.allType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllType([NotNull] GiraphParser.AllTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.allType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllType([NotNull] GiraphParser.AllTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.allTypeWithColl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllTypeWithColl([NotNull] GiraphParser.AllTypeWithCollContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.allTypeWithColl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllTypeWithColl([NotNull] GiraphParser.AllTypeWithCollContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collectionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionDcl([NotNull] GiraphParser.CollectionDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collectionDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionDcl([NotNull] GiraphParser.CollectionDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collectionAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionAssignment([NotNull] GiraphParser.CollectionAssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collectionAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionAssignment([NotNull] GiraphParser.CollectionAssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetQuery([NotNull] GiraphParser.SetQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetQuery([NotNull] GiraphParser.SetQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.graphSetQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGraphSetQuery([NotNull] GiraphParser.GraphSetQueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.graphSetQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGraphSetQuery([NotNull] GiraphParser.GraphSetQueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setExpressionAtri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpressionAtri([NotNull] GiraphParser.SetExpressionAtriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setExpressionAtri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpressionAtri([NotNull] GiraphParser.SetExpressionAtriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setExpressionVari"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpressionVari([NotNull] GiraphParser.SetExpressionVariContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setExpressionVari"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpressionVari([NotNull] GiraphParser.SetExpressionVariContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.compoundAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundAssign([NotNull] GiraphParser.CompoundAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.compoundAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundAssign([NotNull] GiraphParser.CompoundAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] GiraphParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] GiraphParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.setOneAttri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetOneAttri([NotNull] GiraphParser.SetOneAttriContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.setOneAttri"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetOneAttri([NotNull] GiraphParser.SetOneAttriContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collNoReturnOps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollNoReturnOps([NotNull] GiraphParser.CollNoReturnOpsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collNoReturnOps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollNoReturnOps([NotNull] GiraphParser.CollNoReturnOpsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.collReturnOps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollReturnOps([NotNull] GiraphParser.CollReturnOpsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.collReturnOps"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollReturnOps([NotNull] GiraphParser.CollReturnOpsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.enqueueOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnqueueOP([NotNull] GiraphParser.EnqueueOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.enqueueOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnqueueOP([NotNull] GiraphParser.EnqueueOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dequeueOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDequeueOP([NotNull] GiraphParser.DequeueOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dequeueOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDequeueOP([NotNull] GiraphParser.DequeueOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.popOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPopOP([NotNull] GiraphParser.PopOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.popOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPopOP([NotNull] GiraphParser.PopOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.pushOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPushOP([NotNull] GiraphParser.PushOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.pushOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPushOP([NotNull] GiraphParser.PushOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extractMinOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractMinOP([NotNull] GiraphParser.ExtractMinOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extractMinOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractMinOP([NotNull] GiraphParser.ExtractMinOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.extractMaxOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtractMaxOP([NotNull] GiraphParser.ExtractMaxOPContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.extractMaxOP"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtractMaxOP([NotNull] GiraphParser.ExtractMaxOPContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] GiraphParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] GiraphParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.printOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintOptions([NotNull] GiraphParser.PrintOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.printOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintOptions([NotNull] GiraphParser.PrintOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.printOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintOption([NotNull] GiraphParser.PrintOptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.printOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintOption([NotNull] GiraphParser.PrintOptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrint([NotNull] GiraphParser.PrintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrint([NotNull] GiraphParser.PrintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.dequeueOPOneLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDequeueOPOneLine([NotNull] GiraphParser.DequeueOPOneLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.dequeueOPOneLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDequeueOPOneLine([NotNull] GiraphParser.DequeueOPOneLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.commentLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentLine([NotNull] GiraphParser.CommentLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.commentLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentLine([NotNull] GiraphParser.CommentLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GiraphParser.comments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComments([NotNull] GiraphParser.CommentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GiraphParser.comments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComments([NotNull] GiraphParser.CommentsContext context);
}
